import gcsfs
import os
import urllib.request

hapnest_ftp_base = 'ftp://ftp.ebi.ac.uk//biostudies/fire/S-BSST/936/S-BSST936/Files/example/'
hapnest_example_files = [
    'synthetic_small_v1_chr-10.bed',
    'synthetic_small_v1_chr-10.bim',
    'synthetic_small_v1_chr-10.fam',
    'synthetic_small_v1_chr-10.sample',
    'synthetic_small_v1_chr-11.bed',
    'synthetic_small_v1_chr-11.bim',
    'synthetic_small_v1_chr-11.fam',
    'synthetic_small_v1_chr-11.sample',
    'synthetic_small_v1_chr-12.bed',
    'synthetic_small_v1_chr-12.bim',
    'synthetic_small_v1_chr-12.fam',
    'synthetic_small_v1_chr-12.sample',
    'synthetic_small_v1_chr-13.bed',
    'synthetic_small_v1_chr-13.bim',
    'synthetic_small_v1_chr-13.fam',
    'synthetic_small_v1_chr-13.sample',
    'synthetic_small_v1_chr-14.bed',
    'synthetic_small_v1_chr-14.bim',
    'synthetic_small_v1_chr-14.fam',
    'synthetic_small_v1_chr-14.sample',
    'synthetic_small_v1_chr-15.bed',
    'synthetic_small_v1_chr-15.bim',
    'synthetic_small_v1_chr-15.fam',
    'synthetic_small_v1_chr-15.sample',
    'synthetic_small_v1_chr-16.bed',
    'synthetic_small_v1_chr-16.bim',
    'synthetic_small_v1_chr-16.fam',
    'synthetic_small_v1_chr-16.sample',
    'synthetic_small_v1_chr-17.bed',
    'synthetic_small_v1_chr-17.bim',
    'synthetic_small_v1_chr-17.fam',
    'synthetic_small_v1_chr-17.sample',
    'synthetic_small_v1_chr-18.bed',
    'synthetic_small_v1_chr-18.bim',
    'synthetic_small_v1_chr-18.fam',
    'synthetic_small_v1_chr-18.sample',
    'synthetic_small_v1_chr-19.bed',
    'synthetic_small_v1_chr-19.bim',
    'synthetic_small_v1_chr-19.fam',
    'synthetic_small_v1_chr-19.sample',
    'synthetic_small_v1_chr-1.bed',
    'synthetic_small_v1_chr-1.bim',
    'synthetic_small_v1_chr-1.fam',
    'synthetic_small_v1_chr-1.sample',
    'synthetic_small_v1_chr-20.bed',
    'synthetic_small_v1_chr-20.bim',
    'synthetic_small_v1_chr-20.fam',
    'synthetic_small_v1_chr-20.sample',
    'synthetic_small_v1_chr-21.bed',
    'synthetic_small_v1_chr-21.bim',
    'synthetic_small_v1_chr-21.fam',
    'synthetic_small_v1_chr-21.sample',
    'synthetic_small_v1_chr-22.bed',
    'synthetic_small_v1_chr-22.bim',
    'synthetic_small_v1_chr-22.fam',
    'synthetic_small_v1_chr-22.sample',
    'synthetic_small_v1_chr-2.bed',
    'synthetic_small_v1_chr-2.bim',
    'synthetic_small_v1_chr-2.fam',
    'synthetic_small_v1_chr-2.sample',
    'synthetic_small_v1_chr-3.bed',
    'synthetic_small_v1_chr-3.bim',
    'synthetic_small_v1_chr-3.fam',
    'synthetic_small_v1_chr-3.sample',
    'synthetic_small_v1_chr-4.bed',
    'synthetic_small_v1_chr-4.bim',
    'synthetic_small_v1_chr-4.fam',
    'synthetic_small_v1_chr-4.sample',
    'synthetic_small_v1_chr-5.bed',
    'synthetic_small_v1_chr-5.bim',
    'synthetic_small_v1_chr-5.fam',
    'synthetic_small_v1_chr-5.sample',
    'synthetic_small_v1_chr-6.bed',
    'synthetic_small_v1_chr-6.bim',
    'synthetic_small_v1_chr-6.fam',
    'synthetic_small_v1_chr-6.sample',
    'synthetic_small_v1_chr-7.bed',
    'synthetic_small_v1_chr-7.bim',
    'synthetic_small_v1_chr-7.fam',
    'synthetic_small_v1_chr-7.sample',
    'synthetic_small_v1_chr-8.bed',
    'synthetic_small_v1_chr-8.bim',
    'synthetic_small_v1_chr-8.fam',
    'synthetic_small_v1_chr-8.sample',
    'synthetic_small_v1_chr-9.bed',
    'synthetic_small_v1_chr-9.bim',
    'synthetic_small_v1_chr-9.fam',
    'synthetic_small_v1_chr-9.sample',
    'synthetic_small_v1.pheno1',
    'synthetic_small_v1.pheno2',
    'synthetic_small_v1.pheno3',
    'synthetic_small_v1.pheno4',
    'synthetic_small_v1.pheno5',
    'synthetic_small_v1.pheno6',
    'synthetic_small_v1.pheno7',
    'synthetic_small_v1.pheno8',
    'synthetic_small_v1.pheno9',
]

fs = gcsfs.GCSFileSystem(project='', token='')

for f in hapnest_example_files:
    print('Downloading', f)
    urllib.request.urlretrieve(hapnest_ftp_base+f, f)
    fs.put(f, 'hapnest/example/'+f)
    os.remove(f)
